name: sharp
description: A payment solution via QR codes


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^0.1.2
  flutter_barcode_scanner: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - images/qr-code.png
    - scan.png
    - man.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Ubuntu-Light.ttf

